// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {

    "identify-and-password": {
      name: "identify-and-password",
      description: "",
      type: "registry:form",
      registryDependencies: undefined,
      link: "sign-in",
      files: [{
        path: "src/registry/forms/identify-and-password/sign-in/page.tsx",
        type: "registry:page",
        target: "app/sign-in/page.tsx"
      },{
        path: "src/registry/forms/identify-and-password/sign-up/page.tsx",
        type: "registry:page",
        target: "app/sign-up/page.tsx"
      },{
        path: "src/registry/forms/identify-and-password/sign-in/sign-in-form.tsx",
        type: "registry:component",
        target: "components/forms/identify-and-password/sign-in-form.tsx"
      },{
        path: "src/registry/forms/identify-and-password/sign-up/sign-up-form.tsx",
        type: "registry:component",
        target: "components/forms/identify-and-password/sign-up-form.tsx"
      }],
      component: React.lazy(() => import("@/registry/forms/identify-and-password/sign-in/page.tsx")),
      source: "",
      category: "",
      subcategory: "",
      isDummy: false,
      chunks: []
    },
    "sign-up": {
      name: "sign-up",
      description: "",
      type: "registry:form",
      registryDependencies: undefined,
      link: "sign-up",
      files: [{
        path: "src/registry/forms/identify-and-password/sign-up/page.tsx",
        type: "registry:page",
        target: "app/sign-up/page.tsx"
      }],
      component: React.lazy(() => import("@/registry/forms/identify-and-password/sign-up/page.tsx")),
      source: "",
      category: "",
      subcategory: "",
      isDummy: true,
      chunks: []
    },
}
